### ISSUE TITLE
Illumination throws ValueError

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MixerControl#134]
```
/home/mixer/.pm2/logs/MixerControl-error.log last 15 lines:
0|MixerCon |     at Object.onceWrapper (events.js:254:19)
0|MixerCon |     at IncomingMessage.emit (events.js:164:20)
0|MixerCon |     at endReadableNT (_stream_readable.js:1062:12)
0|MixerCon | undefined
0|MixerCon | Error: Bad Gateway
0|MixerCon |     at exports.Logger.logger.logRequestAndResponse (/home/mixer/MixerControl/MixerControl-app/global/logger.js:154:16)
0|MixerCon |     at Request._callback (/home/mixer/MixerControl/MixerControl-app/adapter/juice_machine_service_adapter.js:41:28)
0|MixerCon |     at Request.self.callback (/home/mixer/MixerControl/MixerControl-app/node_modules/request/request.js:186:22)
0|MixerCon |     at Request.emit (events.js:159:13)
0|MixerCon |     at Request.<anonymous> (/home/mixer/MixerControl/MixerControl-app/node_modules/request/request.js:1163:10)
0|MixerCon |     at Request.emit (events.js:159:13)
0|MixerCon |     at IncomingMessage.<anonymous> (/home/mixer/MixerControl/MixerControl-app/node_modules/request/request.js:1085:12)
0|MixerCon |     at Object.onceWrapper (events.js:254:19)
0|MixerCon |     at IncomingMessage.emit (events.js:164:20)
0|MixerCon |     at endReadableNT (_stream_readable.js:1062:12)

/home/mixer/.pm2/logs/Illumination-error.log last 15 lines:
4|Illumina | WARNING:socketIO-client-2:localhost:3000/socket.io [connection error] recv disconnected (Connection is already closed.)
4|Illumina | WARNING:socketIO-client-2:localhost:3000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1519040518065-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bf5170>: Failed to establish a new connection: [Errno 111] Connection refused',))
4|Illumina | WARNING:socketIO-client-2:localhost:3000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1519040519076-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bef250>: Failed to establish a new connection: [Errno 111] Connection refused',))
4|Illumina | WARNING:socketIO-client-2:localhost:3000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1519040520089-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bef050>: Failed to establish a new connection: [Errno 111] Connection refused',))
4|Illumina | WARNING:socketIO-client-2:localhost:3000/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1519040521102-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bea150>: Failed to establish a new connection: [Errno 111] Connection refused',))
4|Illumina | Exception in thread DotStars:
4|Illumina | Traceback (most recent call last):
4|Illumina |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
4|Illumina |     self.run()
4|Illumina |   File "/home/mixer/MixerControl/Illumination/main.py", line 188, in run
4|Illumina |     column = Image.alpha_composite(column, progress)
4|Illumina |   File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2367, in alpha_composite
4|Illumina |     return im1._new(core.alpha_composite(im1.im, im2.im))
4|Illumina | ValueError: images do not match
4|Illumina | 
```

**Comment by bockha** [comment]
likely closed by 9a20b70977d65237b6cfc7b9db97f82fedbd7932
